config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: "users#index"
  end

  resources :posts do
    member do
      get :approve
    end
  end
  resources :audit_logs, except: [:new, :edit, :destory] do
    member do
      get :confirm
    end
  end

  devise_for :users, skip: [:registrations]
  devise_scope :user do
    authenticated :user do
      root 'static#homepage'
    end

    unauthenticated do
      root 'devise/sessions#new'
    end
  end
end

app/views/shared/_admin_dropdown.html.erb
<%= link_to "Admin Dashboard", admin_root_path, class: "dropdown-item"%>

<div class="dropdown-divider"></div>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Overtime App Alert", sticky: false, on_click: remove_gritter) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Overtime App Error", sticky: false, on_click: remove_gritter) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Overtime App Notification", sticky: false, on_click: remove_gritter) %>
<% end %>

app/views/shared/_application_navbar.html.erb
<% if current_user %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to(image_tag("bootstrap-solid.svg", size: "30x30", class: "d-inline-block align-top"), root_path, class: "navbar-brand") %>
    <b><%= link_to "Overtime Application", root_path, class: "nav-link" %></b>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= active?(root_path) %>">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <%= render 'shared/employee_nav_items' if employee? %>
        <%= render 'shared/audit_log_tab' if admin? %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%=current_user.full_name%>
            <br>
            <%= current_user.user_type%>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="right: 0; left: auto;">
            <%= render 'shared/admin_dropdown' if admin? %>

            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>

    </div>
  </nav>
<% end %>

app/views/shared/_audit_log_tab.html.erb
<li class="nav-item <%= active?(audit_logs_path) %>">
  <%= link_to "Audit Log", audit_logs_path, class: "nav-link"%>
</li>

app/views/shared/_employee_nav_items.html.erb
<li class="nav-item <%= active?(posts_path) %>">
  <%= link_to "Entries", posts_path, class: "nav-link" %>
</li>

<li class="nav-item <%= active?(new_post_path) %>">
  <%= link_to "Request Overtime", new_post_path, id: 'new_post_from_nav', class: "nav-link" %>
</li>

app/views/shared/_pagination.html.erb
<div class="pagination justify-content-center" id="paginator">
  <%= paginate object_to_paginate, remote: true %>
</div>